"""empty message

Revision ID: de1f989f11e3
Revises: 152ee6644b2e
Create Date: 2022-05-17 12:01:34.741109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de1f989f11e3'
down_revision = '152ee6644b2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('username', sa.String(length=20), nullable=False))
    op.create_unique_constraint(None, 'comment', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comment', type_='unique')
    op.drop_column('comment', 'username')
    # ### end Alembic commands ###
